In [1]:
import pandas as pd
import numpy as np

In [2]:
# Task 1 : To make three dataframes in python and save them as three .csv files 

# Employee DataFrame
employee = pd.DataFrame({ 
    "ID": ["A001","A002","A003","A004","A005"],
    "Name": ["John Alter","Alice Luxumberg","Tom Sabestine","Nina Adgra","Amy Johny"],
    "Gender": ["M","F","M","F","F"],
    "City": ["Paris","London","Berlin","Newyork","Madrid"],
    "Age": [25,27,29,31,30] })

# Seniority DataFrame
seniority = pd.DataFrame({
    "ID": ["A001","A002","A003","A004","A005"],
    "Designation Level": [2,2,3,2,3] })

# Project DataFrame
project = pd.DataFrame({
    "ID": ["A001","A002","A003","A004","A005","A002","A005","A003","A001","A003","A001","A004","A004","A005"],
    "Project": ["Project 1","Project 2","Project 3","Project 4","Project 5","Project 6","Project 7","Project 8","Project 9","Project 10","Project 11","Project 12","Project 13","Project 14"],
    "Cost": [1002000,2000000,4500000,5500000,np.nan,680000,400000,350000,np.nan,300000,2000000,1000000,3000000,200000],
    "Status": ["Finished","Ongoing","Finished","Ongoing","Finished","Failed","Finished","Failed","Ongoing","Finished","Failed","Ongoing","Finished","Finished"] })

In [3]:
# Saving dataframes as CSV files
employee.to_csv("employee.csv", index=False)
seniority.to_csv("seniority.csv", index=False)
project.to_csv("project.csv", index=False)

In [4]:
# Reloading data from CSV files
employee = pd.read_csv("employee.csv")
seniority = pd.read_csv("seniority.csv")
project = pd.read_csv("project.csv")

In [5]:
# Task 2 : To replace missing values for running average
running_sum = 0
count = 0

# Loop through each row
for i in range(len(project)):
    
# If value is NOT missing
    if not pd.isna(project.loc[i, "Cost"]): 
        running_sum += project.loc[i, "Cost"]
        count += 1
    
# If value is missing
    else:
        project.loc[i, "Cost"] = running_sum / count

project

      ID     Project          Cost    Status
0   A001   Project 1  1.002000e+06  Finished
1   A002   Project 2  2.000000e+06   Ongoing
2   A003   Project 3  4.500000e+06  Finished
3   A004   Project 4  5.500000e+06   Ongoing
4   A005   Project 5  3.250500e+06  Finished
5   A002   Project 6  6.800000e+05    Failed
6   A005   Project 7  4.000000e+05  Finished
7   A003   Project 8  3.500000e+05    Failed
8   A001   Project 9  2.061714e+06   Ongoing
9   A003  Project 10  3.000000e+05  Finished
10  A001  Project 11  2.000000e+06    Failed
11  A004  Project 12  1.000000e+06   Ongoing
12  A004  Project 13  3.000000e+06  Finished
13  A005  Project 14  2.000000e+05  Finished

In [6]:
# Task 3 : To split the name into First and Last
employee[["First Name","Last Name"]] = employee["Name"].str.split(" ", expand=True)

# Drop original column
employee.drop("Name", axis=1, inplace=True)

employee

     ID Gender     City  Age First Name  Last Name
0  A001      M    Paris   25       John      Alter
1  A002      F   London   27      Alice  Luxumberg
2  A003      M   Berlin   29        Tom  Sabestine
3  A004      F  Newyork   31       Nina      Adgra
4  A005      F   Madrid   30        Amy      Johny

In [7]:
# Task 4 : To merge all datasets in to one single dataframe
final = pd.merge(employee, seniority, on="ID")
final = pd.merge(final, project, on="ID")

final

,ID,Gender,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status
0,A001,M,Paris,25,John,Alter,2,Project 1,1.002000e+06,Finished
1,A001,M,Paris,25,John,Alter,2,Project 9,2.061714e+06,Ongoing
2,A001,M,Paris,25,John,Alter,2,Project 11,2.000000e+06,Failed
3,A002,F,London,27,Alice,Luxumberg,2,Project 2,2.000000e+06,Ongoing
4,A002,F,London,27,Alice,Luxumberg,2,Project 6,6.800000e+05,Failed
5,A003,M,Berlin,29,Tom,Sabestine,3,Project 3,4.500000e+06,Finished
6,A003,M,Berlin,29,Tom,Sabestine,3,Project 8,3.500000e+05,Failed
7,A003,M,Berlin,29,Tom,Sabestine,3,Project 10,3.000000e+05,Finished
8,A004,F,Newyork,31,Nina,Adgra,2,Project 4,5.500000e+06,Ongoing
9,A004,F,Newyork,31,Nina,Adgra,2,Project 12,1.000000e+06,Ongoing
10,A004,F,Newyork,31,Nina,Adgra,2,Project 13,3.000000e+06,Finished
11,A005,F,Madrid,30,Amy,Johny,3,Project 5,3.250500e+06,Finished
12,A005,F,Madrid,30,Amy,Johny,3,Project 7,4.000000e+05,Finished
13,A005,F,Madrid,30,Amy,Johny,3,Project 14,2.000000e+05,Finished

In [8]:
# Task 5 : To add bonus column
final["Bonus"] = np.where(final["Status"] == "Finished",
                          final["Cost"] * 0.05,
                          0)

final

,ID,Gender,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
0,A001,M,Paris,25,John,Alter,2,Project 1,1.002000e+06,Finished,50100.0
1,A001,M,Paris,25,John,Alter,2,Project 9,2.061714e+06,Ongoing,0.0
2,A001,M,Paris,25,John,Alter,2,Project 11,2.000000e+06,Failed,0.0
3,A002,F,London,27,Alice,Luxumberg,2,Project 2,2.000000e+06,Ongoing,0.0
4,A002,F,London,27,Alice,Luxumberg,2,Project 6,6.800000e+05,Failed,0.0
5,A003,M,Berlin,29,Tom,Sabestine,3,Project 3,4.500000e+06,Finished,225000.0
6,A003,M,Berlin,29,Tom,Sabestine,3,Project 8,3.500000e+05,Failed,0.0
7,A003,M,Berlin,29,Tom,Sabestine,3,Project 10,3.000000e+05,Finished,15000.0
8,A004,F,Newyork,31,Nina,Adgra,2,Project 4,5.500000e+06,Ongoing,0.0
9,A004,F,Newyork,31,Nina,Adgra,2,Project 12,1.000000e+06,Ongoing,0.0
10,A004,F,Newyork,31,Nina,Adgra,2,Project 13,3.000000e+06,Finished,150000.0
11,A005,F,Madrid,30,Amy,Johny,3,Project 5,3.250500e+06,Finished,162525.0
12,A005,F,Madrid,30,Amy,Johny,3,Project 7,4.000000e+05,Finished,20000.0
13,A005,F,Madrid,30,Amy,Johny,3,Project 14,2.000000e+05,Finished,10000.0

In [9]:
# Task 6 : Demote employees with failed projects

final.loc[final["Status"] == "Failed", "Designation Level"] += 1

# Remove employees with designation > 4
final = final[final["Designation Level"] <= 4]

final

,ID,Gender,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
0,A001,M,Paris,25,John,Alter,2,Project 1,1.002000e+06,Finished,50100.0
1,A001,M,Paris,25,John,Alter,2,Project 9,2.061714e+06,Ongoing,0.0
2,A001,M,Paris,25,John,Alter,3,Project 11,2.000000e+06,Failed,0.0
3,A002,F,London,27,Alice,Luxumberg,2,Project 2,2.000000e+06,Ongoing,0.0
4,A002,F,London,27,Alice,Luxumberg,3,Project 6,6.800000e+05,Failed,0.0
5,A003,M,Berlin,29,Tom,Sabestine,3,Project 3,4.500000e+06,Finished,225000.0
6,A003,M,Berlin,29,Tom,Sabestine,4,Project 8,3.500000e+05,Failed,0.0
7,A003,M,Berlin,29,Tom,Sabestine,3,Project 10,3.000000e+05,Finished,15000.0
8,A004,F,Newyork,31,Nina,Adgra,2,Project 4,5.500000e+06,Ongoing,0.0
9,A004,F,Newyork,31,Nina,Adgra,2,Project 12,1.000000e+06,Ongoing,0.0
10,A004,F,Newyork,31,Nina,Adgra,2,Project 13,3.000000e+06,Finished,150000.0
11,A005,F,Madrid,30,Amy,Johny,3,Project 5,3.250500e+06,Finished,162525.0
12,A005,F,Madrid,30,Amy,Johny,3,Project 7,4.000000e+05,Finished,20000.0
13,A005,F,Madrid,30,Amy,Johny,3,Project 14,2.000000e+05,Finished,10000.0

In [10]:
# Task 7 : To add Mr. & Mrs.
final["First Name"] = np.where(final["Gender"] == "M",
                              "Mr. " + final["First Name"],
                              "Mrs. " + final["First Name"])

# Drop Gender column
final.drop("Gender", axis=1, inplace=True)

final

,ID,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
0,A001,Paris,25,Mr. John,Alter,2,Project 1,1.002000e+06,Finished,50100.0
1,A001,Paris,25,Mr. John,Alter,2,Project 9,2.061714e+06,Ongoing,0.0
2,A001,Paris,25,Mr. John,Alter,3,Project 11,2.000000e+06,Failed,0.0
3,A002,London,27,Mrs. Alice,Luxumberg,2,Project 2,2.000000e+06,Ongoing,0.0
4,A002,London,27,Mrs. Alice,Luxumberg,3,Project 6,6.800000e+05,Failed,0.0
5,A003,Berlin,29,Mr. Tom,Sabestine,3,Project 3,4.500000e+06,Finished,225000.0
6,A003,Berlin,29,Mr. Tom,Sabestine,4,Project 8,3.500000e+05,Failed,0.0
7,A003,Berlin,29,Mr. Tom,Sabestine,3,Project 10,3.000000e+05,Finished,15000.0
8,A004,Newyork,31,Mrs. Nina,Adgra,2,Project 4,5.500000e+06,Ongoing,0.0
9,A004,Newyork,31,Mrs. Nina,Adgra,2,Project 12,1.000000e+06,Ongoing,0.0
10,A004,Newyork,31,Mrs. Nina,Adgra,2,Project 13,3.000000e+06,Finished,150000.0
11,A005,Madrid,30,Mrs. Amy,Johny,3,Project 5,3.250500e+06,Finished,162525.0
12,A005,Madrid,30,Mrs. Amy,Johny,3,Project 7,4.000000e+05,Finished,20000.0
13,A005,Madrid,30,Mrs. Amy,Johny,3,Project 14,2.000000e+05,Finished,10000.0

In [11]:
# Task 8 : To promote if age > 29

final.loc[final["Age"] > 29, "Designation Level"] -= 1
final

,ID,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
0,A001,Paris,25,Mr. John,Alter,2,Project 1,1.002000e+06,Finished,50100.0
1,A001,Paris,25,Mr. John,Alter,2,Project 9,2.061714e+06,Ongoing,0.0
2,A001,Paris,25,Mr. John,Alter,3,Project 11,2.000000e+06,Failed,0.0
3,A002,London,27,Mrs. Alice,Luxumberg,2,Project 2,2.000000e+06,Ongoing,0.0
4,A002,London,27,Mrs. Alice,Luxumberg,3,Project 6,6.800000e+05,Failed,0.0
5,A003,Berlin,29,Mr. Tom,Sabestine,3,Project 3,4.500000e+06,Finished,225000.0
6,A003,Berlin,29,Mr. Tom,Sabestine,4,Project 8,3.500000e+05,Failed,0.0
7,A003,Berlin,29,Mr. Tom,Sabestine,3,Project 10,3.000000e+05,Finished,15000.0
8,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 4,5.500000e+06,Ongoing,0.0
9,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 12,1.000000e+06,Ongoing,0.0
10,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 13,3.000000e+06,Finished,150000.0
11,A005,Madrid,30,Mrs. Amy,Johny,2,Project 5,3.250500e+06,Finished,162525.0
12,A005,Madrid,30,Mrs. Amy,Johny,2,Project 7,4.000000e+05,Finished,20000.0
13,A005,Madrid,30,Mrs. Amy,Johny,2,Project 14,2.000000e+05,Finished,10000.0

In [12]:
# Task 9 : To group and calculate total cost

total_proj_cost = final.groupby(["ID","First Name"])["Cost"].sum().reset_index()

# Rename column
total_proj_cost.rename(columns={"Cost": "Total Cost"}, inplace=True)

total_proj_cost

     ID  First Name    Total Cost
0  A001    Mr. John  5.063714e+06
1  A002  Mrs. Alice  2.680000e+06
2  A003     Mr. Tom  5.150000e+06
3  A004   Mrs. Nina  9.500000e+06
4  A005    Mrs. Amy  3.850500e+06

In [13]:
# Task 10 : Filtering cities with 'o'

result = final[final["City"].str.contains("o", case=False)]

result

,ID,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
3,A002,London,27,Mrs. Alice,Luxumberg,2,Project 2,2000000.0,Ongoing,0.0
4,A002,London,27,Mrs. Alice,Luxumberg,3,Project 6,680000.0,Failed,0.0
8,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 4,5500000.0,Ongoing,0.0
9,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 12,1000000.0,Ongoing,0.0
10,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 13,3000000.0,Finished,150000.0